### ISSUE TITLE
Web-fragment.xml causes probelms on weblogic

### ISSUE THREAD

**Issue by 99sono** [rdebusscher/AdvancedGraphicImageRenderer#1]
HI,

The web-fragment.xml and its namespaces is problematic for weblogic using the old j2ee namespace.
In addition, the listener declares a listener that does not need to be declared under JEE6.

Bellow is the weblogic exception.
<code>
<Jun 1, 2015 9:50:59 AM CEST> <Error> <Munger> <WL-2156200> <Unable to load descriptor weblogic.utils.classloaders.GenericClassLoader@67a2129f finder: weblogic.utils.classloaders.CodeGenClassFinder@2143fdfd annotation: jsf_deltaspike-dynamic-content_war_1.0-SNAPSHOT@/WEB-INF/lib/advanced-graphic-image.jar!/META-INF/web-fragment.xml of module jsf-viewaccessscoped. The error is weblogic.descriptor.DescriptorException: VALIDATION PROBLEMS WERE FOUND
  D:\WM6APPS\Weblogic\user_projects\domains\techlab\weblogic.utils.classloaders.GenericClassLoader@67a2129f finder: weblogic.utils.classloaders.CodeGenClassFinder@2143fdfd annotation: 
  jsf_deltaspike-dynamic-content_war_1.0-SNAPSHOT@\
  WEB-INF\lib\advanced-graphic-image.jar!
  \META-INF\web-fragment.xml:20:3:20:3: problem: 
  cvc-enumeration-valid: string value '3.0' is not a valid enumeration value for web-app-versionType in namespace http://java.sun.com/xml/ns/j2ee
    at weblogic.descriptor.internal.MarshallerFactory$1.evaluateResults(MarshallerFactory.java:245)
    at weblogic.descriptor.internal.MarshallerFactory$1.evaluateResults(MarshallerFactory.java:231)
    at weblogic.descriptor.internal.MarshallerFactory$1.createDescriptor(MarshallerFactory.java:155)
    at weblogic.descriptor.BasicDescriptorManager.createDescriptor(BasicDescriptorManager.java:326)
    at weblogic.application.descriptor.AbstractDescriptorLoader2.getDescriptorBeanFromReader(AbstractDescriptorLoader2.java:807)
    at weblogic.application.descriptor.AbstractDescriptorLoader2.createDescriptorBean(AbstractDescriptorLoader2.java:415)
    at weblogic.application.descriptor.AbstractDescriptorLoader2.loadDescriptorBeanWithoutPlan(AbstractDescriptorLoader2.java:778)
    at weblogic.application.descriptor.AbstractDescriptorLoader2.loadDescriptorBean(AbstractDescriptorLoader2.java:787)
    at weblogic.servlet.internal.fragment.WebFragmentLoader.getWebFragmentBean(WebFragmentLoader.java:36)
    at weblogic.servlet.internal.fragment.WebFragmentManager.prepareForTopologicalSort(WebFragmentManager.java:163)
    at weblogic.servlet.internal.fragment.WebFragmentManager.sortRelatively(WebFragmentManager.java:151)
    at weblogic.servlet.internal.fragment.WebFragmentManager.sortFragments(WebFragmentManager.java:108)
    at weblogic.servlet.internal.fragment.WebFragmentManager.<init>(WebFragmentManager.java:53)
    at weblogic.servlet.internal.fragment.WebFragmentManager.<init>(WebFragmentManager.java:42)
    at weblogic.servlet.internal.WebAppModule.initWebFragmentManager(WebAppModule.java:637)
    at weblogic.servlet.internal.WebAppModule.prepare(WebAppModule.java:762)
    at weblogic.application.internal.ExtensibleModuleWrapper$PrepareStateChange.next(ExtensibleModuleWrapper.java:295)
    at weblogic.application.internal.ExtensibleModuleWrapper$PrepareStateChange.next(ExtensibleModuleWrapper.java:285)
    at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:42)
    at weblogic.application.internal.ExtensibleModuleWrapper.prepare(ExtensibleModuleWrapper.java:109)
    at weblogic.application.internal.flow.ModuleListenerInvoker.prepare(ModuleListenerInvoker.java:100)
    at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:172)
    at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:167)
    at weblogic.application.utils.StateMachineDriver$ParallelChange.run(StateMachineDriver.java:80)
    at weblogic.work.ContextWrap.run(ContextWrap.java:40)
    at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:550)
    at weblogic.work.ExecuteThread.execute(ExecuteThread.java:295)
    at weblogic.work.ExecuteThread.run(ExecuteThread.java:254)
</code>

To deploy the application using the library I needed convert the web-fragment.xml to:

<code>
<web-fragment version="3.0" xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-fragment_3_0.xsd">

```
<!--
    THe following listener does not NEED to be declared:
    REFERENCE: http://www.coderanch.com/how-to/java/DeclaringListeners
    QUOTE:  
        The main point is : Classes implementing interfaces other than HttpSessionBindingListener and HttpSessionActivationListener need to be declared in DD.             
-->
<!--listener>
    <description>HttpSessionBindingListener</description>
    <listener-class>be.rubus.web.jsf.primefaces.GraphicImageManager</listener-class>
</listener-->
```

</web-fragment>

</code>

**Comment by rdebusscher** [comment]
WebFragments are added in Web Servlets 3.0.  So when WebLogic refuses the version number, it seems an issue with WebLogic.

**Comment by rdebusscher** [comment]
The Listener is defined (if I'm not mistaken) for other environments like Tomcat.

**Comment by 99sono** [comment]
Hi there,
Weblogic seems to be supporting the web-fragment, but under the namespaces that we see for deltaspike jee6-impl, for example.

The listener definition was straight out refused by weblogic, stating that the given listener does not implement the proper listener APIs. The error also seems to be consistent with the the forum entry I added as reference.

I will have to check that the deployment with the web-fragment.xml as I've suggested also goes through on glassfish 3.1.2.X. If so I will provide you an update.

Just a side node - on the fork I created, I am mainly interested in making sure that the branch:
https://github.com/99sono/AdvancedGraphicImageRenderer/tree/1.0.1-SNAPSHOT

Works without issue, since for the time being we are using primefaces 3.5 and we will not upgrade it this year.

Kindest regards.
