### ISSUE TITLE
UT010012 on wildfly 9.0.2

### ISSUE THREAD

**Issue by vipcxj** [rdebusscher/AdvancedGraphicImageRenderer#10]
Caused by: java.lang.IllegalArgumentException: UT010012: Listener class class be.rubus.web.jsf.primefaces.GraphicImageManager must implement at least one listener interface
    at io.undertow.servlet.api.ListenerInfo.<init>(ListenerInfo.java:41)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService.addListener(UndertowDeploymentInfoService.java:1266)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService.createServletConfig(UndertowDeploymentInfoService.java:823)
    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService.start(UndertowDeploymentInfoService.java:265)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)

Version: 1.2.1

**Comment by rdebusscher** [comment]
Sorry for the late response.

Seems that the definition of the listener isn't needed.

I created a version 1.2.2.

Regards
Rudy
